### PR TITLE
Genome Trackers terms

### PR DESCRIPTION
**Pull request by Anoosha-Sehar**

### CODE REVIEW

**Review by ddooley — CHANGES_REQUESTED** [review]
I don't think we would want a specific "swine heart food product" or "pork heart food product"  .  We already have "swine food product", and your "swine heart" could go under that.  Swine is slightly more encompassing than pork, hence there is a "pork food product" as well, under which "pork heart" can go.

**Comment by Anoosha-Sehar** [comment]
> I don't think we would want a specific "swine heart food product" or "pork heart food product" . We already have "swine food product", and your "swine heart" could go under that. Swine is slightly more encompassing than pork, hence there is a "pork food product" as well, under which "pork heart" can go.

okay, yeah it makes sense. Actually we do have a separate branch 'sheep meat food product' and still we have 'sheep liver (raw)' under both 'sheep meat food product' and 'liver food product'. So thought to follow that. You're right I think we don't need swine/pork heart food food product. But maybe I should add 'swine heart' under both 'swine food product' and 'heart food product', if that makes sense?

**Comment by ddooley** [comment]
I see.  What should happen now anyways is that things like pork liver can be inferred under the liver food product class once basic reasoning is done on FoodOn.  Something to test out soon.

**Comment by Anoosha-Sehar** [comment]
> I see. What should happen now anyways is that things like pork liver can be inferred under the liver food product class once basic reasoning is done on FoodOn. Something to test out soon.

Agreed, that would definitely be great.

**Review by ddooley — APPROVED** [review]

**Pull request merged**
