### PR TITLE
Anoosha_foodon_03

### PR DESCRIPTION
**Pull request by Anoosha-Sehar**
Terms for GRDI

### CODE REVIEW

**Comment by ddooley** [comment]
I'm a little puzzled why the foodon_product_import.ofn file has its classes loosing their names, now just having ID's - this is making for a much bigger diff than would be necessary.  Did protege look odd at top-level when changes were saved? Maybe in a zoom we can quickly go over the save action to see why?

**Comment by Anoosha-Sehar** [comment]
> 

Oh yes, I was wondering the same, but then I thought that maybe because I've opened .ofn format first time in my protege and these might be the recent changes. I even tried redoing the changes a couple of times but foodon_product_import.ofn had the same issue every time. 

I'm on campus, so in case you are planning to come to campus today, then we can meet before the lab meeting. Otherwise, just let me know when you're free to chat on zoom, I can talk anytime.

**Comment by ddooley** [comment]
Are you working on foodon_product_import.ofn directly?  or are you working on foodon-edit.ofn and saving that, with changes percolating out to foodon_product_import.ofn .  The latter should be the way to go.  The former would, if alone cause many labels to be forgotten that were defined in  foodon-edit.ofn  I bet.

**Comment by Anoosha-Sehar** [comment]
Right, then probably that's the issue because I was working directly on foodon_product_import.ofn. Okay, I am going revert those changes and will try the latter option. I'll let you know. 
Thanks alot!!

**Comment by Anoosha-Sehar** [comment]
It's working fine now. Sorry for all the trouble. 
I am closing this pull request, so to avoid any errors. I'll generate a new one in the next couple of hours. 
Thank you, Damion!!

**Comment by ddooley** [comment]
Ok. FYI, you could copy the  foodon_product_import.ofn and foodon-edit.ofn as is in your branch to a new branch of master, then make one tweak on foodon-edit.ofn, and resave, and that would correct all the labels in foodon_product_import.ofn without you having to do any other edits.

**Comment by Anoosha-Sehar** [comment]
Okay, I didn't know that, it's super helpful. 
Noting it down for future edits as well. Thank you.

**Pull request closed without merging**
