### PR TITLE
Issue 300 Creation of animal parts module

### PR DESCRIPTION
**Pull request by kaiiam**
Cross reference to https://github.com/FoodOntology/foodon/issues/300

Additional run information to be added to the documentation for the organism parts modules:

**Test animal parts module:**

```
bash run_organism_parts.sh MODE="test" MODULE="animal" TERM_CONTRIBUTOR_STR="https://orcid.org/0000-0002-3410-4655|https://orcid.org/0000-0002-3410-4655"
```

**Run animal part module:**

```
bash run_organism_parts.sh MODE="run" MODULE="animal" TERM_CONTRIBUTOR_STR="https://orcid.org/0000-0001-5275-8866|https://orcid.org/0000-0002-8844-9165|https://orcid.org/0000-0002-3410-4655|https://orcid.org/0000-0002-3410-4655"
```

**Test plant parts module:**

```
bash run_organism_parts.sh MODE="test" MODULE="plant" TERM_CONTRIBUTOR_STR="https://orcid.org/0000-0002-3410-4655|https://orcid.org/0000-0002-3410-4655"
```

**Run plant parts module:**
```
bash run_organism_parts.sh MODE="run" MODULE="plant" TERM_CONTRIBUTOR_STR="https://orcid.org/0000-0001-5275-8866|https://orcid.org/0000-0002-8844-9165|https://orcid.org/0000-0002-3410-4655|https://orcid.org/0000-0002-3410-4655"
```

### CODE REVIEW

**Comment by kaiiam** [comment]
To add to the docs the dependencies for running the modules: bash (I was using 3.2), python3 (I was using 3.11.4), [robot](http://robot.obolibrary.org/) (I was using 1.9.3).

**Comment by kaiiam** [comment]
Just added the demo SPARQL query script to get at the old APs from the terms in the values block. The query script is run with a command like 
```
robot query --input foodon_merged.owl --query scripts/foodon_extras.sparql results/foodon_extras_metadata.csv
```
Not this is an example command not reflective of the FOODON directory structure.

**Review by ddooley — APPROVED** [review]

**Comment by kaiiam** [comment]
Note that you need to be in `foodon/src/ontology/scripts` to run the commands. To add to the docs about this.

**Comment by kaiiam** [comment]
Note a user will also have to run `make` in order for the commands to work. Note that we probably don't want to commit the local changes to `foodon-merged.ofn` in the workflow we should clarify this in the docs.

**Pull request merged**
