### PR TITLE
Add Damion Dooley term id range

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pbuttigieg** [comment]
I'd rather have ranges for people and an "in_subset " annotation property for groupings like this.

**Comment by Public-Health-Bioinformatics** [comment]
Ok.  I was thinking it might not be just me contributing new items from our ontology group; but if you want it organized by user thats fine.  I just changed to my name.

**Comment by Public-Health-Bioinformatics** [comment]
Pull request now has

```
 allocatedto: "Damion Dooley"
```

**Comment by Public-Health-Bioinformatics** [comment]
Pier, I think this is good to go now, right? https://github.com/FoodOntology/foodon/pull/9/files

**Comment by pbuttigieg** [comment]
Yes, looks good

**Pull request merged**
