### PR TITLE
robot import for #199

### PR DESCRIPTION
**Pull request by cbarcl01**
robot issue import for some terms in issue #199.

### CODE REVIEW

**Review by cmrn-rhi — COMMENTED** [review]
@ddooley do you have an idea of why a bunch of `foodon_product_import.ofn` term labels switched from the onto ID to the proper label? Doesn't seem like a bad thing, just wondering why this might have happened while @cbarcl01 was doing this work.

**Comment by ddooley** [comment]
Two things may be involved.  
FIRST, for robot to work, it just takes an updated foodon-merged.ofn to be aware of all the latest foodon term labels.
Also, for generating foodon-merged.ofn, foodon-edit.ofn needs to have the import files listed in it, as managed by protege.  If an import file is missing, (from perspective of catalog-v001.xml file knowing where the .ofn import files are) then one might be dropped from view in protege when looking at list of imports.  So currently if you synch to github, it can take the presence of catalog-v001.xml for the main foodon file to know local location and import all the imports, thus providing labels.
All this was kinda true in previous foodon setup too.  But some differences may lead to situation you encountered.

**Comment by ddooley** [comment]
So its kind of hard to read the robot-199.ofn .  Can you include the original tsv table in the pull request? All source .tsv files are usually placed in /src/ontology/imports/robot .  

This also raises the question of whether this should remain a separate robot file. If not, then the next step would be to merge directly into foodon-edit.ofn . I can see how maybe we'd just do that as a separate pull request though.

**Comment by ddooley** [comment]
Actually, about merging - product entries would go to foodon-product-import.ofn, and other quality etc terms would go in foodon-edit.ofn.  Which means input term table should be split into respective entries so that resulting foodon products can be shunted to the appropriate import or foodon-edit file.

**Comment by cmrn-rhi** [comment]
> This also raises the question of whether this should remain a separate robot file. If not, then the next step would be to merge directly into foodon-edit.ofn . I can see how maybe we'd just do that as a separate pull request though.

Yes, the expectation was that we wouldn't preserve the robot file since it's a mixed bag of terms. The makefile hasn't been run since @cbarcl01 and I are currently operating on Windows (Linux subsystem not currently set-up) so we were leaving it to you to cover that step. That being said, I can now run it from my work laptop.

> Actually, about merging - product entries would go to foodon-product-import.ofn, and other quality etc terms would go in foodon-edit.ofn. Which means input term table should be split into respective entries so that resulting foodon products can be shunted to the appropriate import or foodon-edit file.

Do we have this captured in a workflow anywhere? And if not, perhaps we could do a more comprehensive version of [this diagram](https://foodon.org/wp-content/uploads/2021/01/image-2.png) to show were specific term groups belong?

**Comment by ddooley** [comment]
Re. Foodon_00004245 and make file error.  I'll fix that. Its supposed to be a definition tag.

**Pull request merged**
