### PR TITLE
Anoosha

### PR DESCRIPTION
**Pull request by Anoosha-Sehar**
Updated the terms in which 'derives from' axiom was pointing towards a deprecated term.(Pass-1)

### CODE REVIEW

**Review by Anoosha-Sehar — COMMENTED** [review]
`salt block for livestock`: Do you think instead of 'derives from', it could be 'has defining ingredient' some 'sodium chloride'?

**Comment by ddooley** [comment]
Hi Anoosha.  I think you edited foodon-merged.owl by accident?  Edits should be showing up in foodon-edit.owl or food_product_import.owl  
As for "salt block for livestock" - yes, defining ingredient is appropriate!

**Comment by Anoosha-Sehar** [comment]
Oops sorry, I thought I confirmed that in slack yesterday that if I should make changes in foodon-merged.owl? but maybe I wasn't very clear. I should have been more specific. 
Also I mentioned that ''I checked if I can make edits in the respective file like (brine is in src/ontology/imports/foodon_product_import.owl) but that does not have 'CHEBI term 'sodium chloride' so I think that's the same problem you mentioned about, that the deprecated terms and the replacement terms are sprinkled around in various import files? 
Considering that, maybe I should make edits in foodon-edit.owl?

**Comment by ddooley** [comment]
You would be opening foodon-edit.owl to make the change, but editing the current axiom by clicking on it, and substituting the non-deprecated term name, e.g. 'derives from' some 'obsolete: X'  -> 'derives from' some 'X' usually in the case of sodium chloride.  But if deleting this and instead making it 'has defining ingredient' some 'sodium chloride', if you just enter that text to replace the current axiom, it will save that wherever the current axiom existed.  But that axiom will usually be located in foodon-edit.owl or food_product_import.owl .  BTW foodon-merged.owl is an output product of foodon-edit.owl in the build process so it isn't ever edited itself.

**Comment by Anoosha-Sehar** [comment]
Yes, I'm exactly editing like this as you mentioned. It's just that I should have done it in foodon-edit.owl instead of foodon-merged. You're right, It makes sense that foodon-merged is an output file. 
I've  checked that foodon-edit.owl allows to replace the deprecated term with non-deprecated one. But foodon_product_import file does not allow that. Products are missing in that file. So it's better that I remake the changes in foodon-edit.owl. 
P.S: Closing this pull request to make a new one.

**Pull request closed without merging**
